#!/usr/bin/env python3
"""Generate the pin boilerplate for a minimig.v testbench.

minimig.v has ~230 ports, nearly all of which have nothing to do with the save
state register bus. Writing them out by hand once is bad enough; keeping them in
step with a module that other work keeps extending is worse, and a bench that
silently loses a port to a rename is a bench that stops proving anything.

So the declarations and the by-name connection list are generated from the
module header itself:

    python3 gen_minimig_pins.py            # rewrites minimig_pins.vh in place
    python3 gen_minimig_pins.py --check    # fails if the checked-in copy is stale

The generated file declares every port as a wire, plus a driver `reg` named
`drv_<port>` for each input, and connects the DUT by name. Inputs are driven
through the reg so a testbench can assign them procedurally; outputs are read
from the wire directly.

The exception is EXTERNAL below: inputs the testbench drives from real RTL
rather than procedurally -- the two amiga_clk instances and ss_regshadow's
replay outputs. Those get a bare wire and no driver, so the bench must connect
them or the DUT sees Z and the run fails loudly.
"""

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MINIMIG_V = os.path.normpath(os.path.join(HERE, "..", "..", "minimig.v"))
OUT_VH = os.path.join(HERE, "minimig_pins.vh")

DIRECTIONS = ("input", "output", "inout")

# Inputs the bench drives from other RTL, not procedurally: the Amiga-side
# clock generator's outputs and ss_regshadow's replay bus.
EXTERNAL = {
    "clk", "clk7_en", "clk7n_en", "c1", "c3", "cck", "eclk",
    "ss_replay_we", "ss_replay_addr", "ss_replay_data", "ss_replay_tick",
}


def read_port_header(path):
    """Return the text between `module minimig (` and the closing `);`."""
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        text = fh.read()

    start = re.search(r"^module\s+minimig\s*$", text, re.MULTILINE)
    if not start:
        raise SystemExit("gen_minimig_pins: no `module minimig` in %s" % path)

    open_paren = text.index("(", start.end())
    depth = 0
    for i in range(open_paren, len(text)):
        if text[i] == "(":
            depth += 1
        elif text[i] == ")":
            depth -= 1
            if depth == 0:
                return text[open_paren + 1:i]
    raise SystemExit("gen_minimig_pins: unterminated port list")


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    text = re.sub(r"//[^\n]*", "", text)
    return text


def parse_ports(header):
    """[(direction, range_or_None, name)] in declaration order."""
    ports = []
    for chunk in strip_comments(header).split(","):
        chunk = chunk.strip()
        if not chunk:
            continue
        m = re.match(
            r"^(input|output|inout)\s+"       # direction
            r"(?:wire\s+|reg\s+)?"            # optional net type
            r"(\[[^\]]*\]\s*)?"               # optional range
            r"([A-Za-z_][A-Za-z0-9_$]*)$",    # name
            " ".join(chunk.split()),
        )
        if not m:
            raise SystemExit("gen_minimig_pins: cannot parse port %r" % chunk)
        direction, rng, name = m.group(1), m.group(2), m.group(3)
        ports.append((direction, (rng or "").strip(), name))
    return ports


def render(ports):
    width = max(len(r) for _, r, _ in ports) if ports else 0
    lines = [
        "// GENERATED by gen_minimig_pins.py -- do not edit.",
        "// Regenerate with: python3 gen_minimig_pins.py",
        "//",
        "// Every minimig.v port as a wire, every input additionally as a `drv_`",
        "// reg that feeds it, and the by-name instantiation. See the generator",
        "// for why this is not written out by hand.",
        "",
        "// ---------------------------------------------------------- port nets",
    ]
    for direction, rng, name in ports:
        pad = rng.ljust(width)
        lines.append("wire %s %s;" % (pad, name))

    lines += ["", "// ------------------------------------------------------- input drivers",
              "// (ports in the generator's EXTERNAL set are left for the bench to drive)"]
    for direction, rng, name in ports:
        if direction == "input" and name not in EXTERNAL:
            pad = rng.ljust(width)
            lines.append("reg  %s drv_%s;" % (pad, name))
    lines.append("")
    for direction, rng, name in ports:
        if direction == "input" and name not in EXTERNAL:
            lines.append("assign %s = drv_%s;" % (name, name))

    lines += ["", "// -------------------------------------------------------- all inputs low",
              "task pins_reset_inputs;", "begin"]
    for direction, rng, name in ports:
        if direction == "input" and name not in EXTERNAL:
            lines.append("\tdrv_%s = 0;" % name)
    lines += ["end", "endtask", "",
              "// ------------------------------------------------------------------ DUT",
              "minimig dut ("]
    conns = ["\t.%s(%s)" % (name, name) for _, _, name in ports]
    lines.append(",\n".join(conns))
    lines.append(");")
    lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if minimig_pins.vh is out of date")
    args = ap.parse_args()

    ports = parse_ports(read_port_header(MINIMIG_V))
    text = render(ports)

    if args.check:
        try:
            # Newline-insensitive: git checks this file out with CRLF on
            # Windows, and a line ending is not a stale port list.
            with open(OUT_VH, "r", encoding="utf-8") as fh:
                current = fh.read().splitlines()
        except FileNotFoundError:
            current = None
        if current != text.splitlines():
            sys.stderr.write(
                "minimig_pins.vh is stale -- minimig.v's port list has changed.\n"
                "Run: python3 rtl/sim/ssmux/gen_minimig_pins.py\n")
            return 1
        print("minimig_pins.vh up to date (%d ports)" % len(ports))
        return 0

    with open(OUT_VH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print("wrote %s (%d ports)" % (OUT_VH, len(ports)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
