// GENERATED by gen_minimig_pins.py -- do not edit.
// Regenerate with: python3 gen_minimig_pins.py
//
// Every minimig.v port as a wire, every input additionally as a `drv_`
// reg that feeds it, and the by-name instantiation. See the generator
// for why this is not written out by hand.

// ---------------------------------------------------------- port nets
wire [23:1]  cpu_address;
wire [15:0]  cpu_data;
wire [15:0]  cpudata_in;
wire [2:0]   _cpu_ipl;
wire         _cpu_as;
wire         _cpu_uds;
wire         _cpu_lds;
wire         cpu_r_w;
wire         _cpu_dtack;
wire         _cpu_reset;
wire         _cpu_reset_in;
wire [31:0]  nmi_addr;
wire         ovr;
wire [15:0]  ram_data;
wire [15:0]  ramdata_in;
wire [23:1]  ram_address;
wire         _ram_bhe;
wire         _ram_ble;
wire         _ram_we;
wire         _ram_oe;
wire [47:0]  chip48;
wire         rst_ext;
wire         rst_out;
wire         clk;
wire         clk7_en;
wire         clk7n_en;
wire         c1;
wire         c3;
wire         cck;
wire [9:0]   eclk;
wire         rxd;
wire         txd;
wire         cts;
wire         rts;
wire         dtr;
wire         dsr;
wire         cd;
wire         ri;
wire [15:0]  _joy1;
wire [15:0]  _joy2;
wire [15:0]  _joy3;
wire [15:0]  _joy4;
wire [15:0]  joya1;
wire [15:0]  joya2;
wire [2:0]   mouse_btn;
wire         kms_level;
wire [1:0]   kbd_mouse_type;
wire [7:0]   kbd_mouse_data;
wire         pwr_led;
wire         fdd_led;
wire         hdd_led;
wire [64:0]  rtc;
wire         IO_UIO;
wire         IO_FPGA;
wire         IO_STROBE;
wire         IO_WAIT;
wire [15:0]  IO_DIN;
wire [15:0]  IO_DOUT;
wire         _hsync;
wire         _vsync;
wire         _csync;
wire         field1;
wire         lace;
wire         hblank;
wire         vblank;
wire [7:0]   red;
wire [7:0]   green;
wire [7:0]   blue;
wire [1:0]   ar;
wire [2:0]   scanline;
wire         ce_pix;
wire [1:0]   res;
wire         ntsc;
wire [14:0]  ldata;
wire [14:0]  rdata;
wire [8:0]   ldata_okk;
wire [8:0]   rdata_okk;
wire [1:0]   aud_mix;
wire         toccata_ena;
wire [7:0]   toccata_base;
wire [15:0]  toccata_aud_left;
wire [15:0]  toccata_aud_right;
wire         a2065_ena;
wire [7:0]   a2065_base;
wire         cdtv_mode;
wire [15:0]  cdtv_din;
wire         cdtv_selack;
wire [5:0]   cdtv_ac_rom_addr;
wire [7:0]   cdtv_ac_rom_byte;
wire         cdtv_cmd_in_pop;
wire         cdtv_cmd_in_pending;
wire [7:0]   cdtv_cmd_in_byte;
wire         cdtv_cmd_out_push;
wire [7:0]   cdtv_cmd_out_data;
wire         cdtv_sec_byte_push;
wire [7:0]   cdtv_sec_byte_data;
wire [7:0]   cdtv_sec_space;
wire         cdtv_sec_fifo_empty;
wire         cdtv_subq_push;
wire [7:0]   cdtv_subq_byte;
wire         cdtv_stch_pulse;
wire         cdtv_stch_ack;
wire         cdtv_stch_ack_clr;
wire         cdtv_sten_pulse;
wire         cdtv_scor_pulse;
wire         cdtv_sbcp_pulse;
wire         cdtv_dma_req;
wire         cdtv_dma_we;
wire [23:0]  cdtv_dma_baddr;
wire [7:0]   cdtv_dma_wbyte;
wire         cdtv_dma_ack;
wire [13:0]  cdtv_nvr_load_addr;
wire [7:0]   cdtv_nvr_load_din;
wire         cdtv_nvr_load_we;
wire [13:0]  cdtv_nvr_save_addr;
wire [7:0]   cdtv_nvr_save_dout;
wire         cdtv_nvr_dirty;
wire         cdtv_nvr_clear_dirty;
wire [9:0]   cdtv_cdda_volume;
wire [1:0]   cpucfg;
wire [3:0]   cachecfg;
wire [6:0]   memcfg;
wire         bootrom;
wire         ide_ena;
wire         ide_fast;
wire         ide_ext_irq;
wire         akiko_irq;
wire [5:0]   ide_req;
wire [4:0]   ide_address;
wire         ide_write;
wire [15:0]  ide_writedata;
wire         ide_read;
wire [15:0]  ide_readdata;
wire         a2065_clk_ddr;
wire [28:0]  a2065_mem_address;
wire [7:0]   a2065_mem_burstcount;
wire         a2065_mem_read;
wire [63:0]  a2065_mem_readdata;
wire         a2065_mem_readdatavalid;
wire [63:0]  a2065_mem_writedata;
wire [7:0]   a2065_mem_byteenable;
wire         a2065_mem_write;
wire         a2065_mem_waitrequest;
wire [6:0]   USER_IN;
wire [6:0]   USER_OUT;
wire [1:0]   user_port_mode;
wire [5:0]   snac_mode;
wire [2:0]   mister_floppy_status;
wire         ss_blit_busy;
wire         ss_disk_busy;
wire         ss_audio_busy;
wire [14:0]  ss_intreq;
wire [14:0]  ss_intena;
wire [8:1]   ss_rga_addr;
wire [15:0]  ss_rga_data;
wire         ss_replay_we;
wire [8:1]   ss_replay_addr;
wire [15:0]  ss_replay_data;
wire         ss_replay_tick;
wire [3:0]   ss_map;
wire [3:0]   ss_map_in;
wire         ss_map_we;
wire [190:0] ss_cia_a;
wire [202:0] ss_cia_b;
wire [190:0] ss_cia_a_in;
wire [202:0] ss_cia_b_in;
wire         ss_cia_we;

// ------------------------------------------------------- input drivers
// (ports in the generator's EXTERNAL set are left for the bench to drive)
reg  [23:1]  drv_cpu_address;
reg  [15:0]  drv_cpudata_in;
reg          drv__cpu_as;
reg          drv__cpu_uds;
reg          drv__cpu_lds;
reg          drv_cpu_r_w;
reg          drv__cpu_reset_in;
reg  [31:0]  drv_nmi_addr;
reg  [15:0]  drv_ramdata_in;
reg  [47:0]  drv_chip48;
reg          drv_rst_ext;
reg          drv_rxd;
reg          drv_cts;
reg          drv_dsr;
reg          drv_cd;
reg          drv_ri;
reg  [15:0]  drv__joy1;
reg  [15:0]  drv__joy2;
reg  [15:0]  drv__joy3;
reg  [15:0]  drv__joy4;
reg  [15:0]  drv_joya1;
reg  [15:0]  drv_joya2;
reg  [2:0]   drv_mouse_btn;
reg          drv_kms_level;
reg  [1:0]   drv_kbd_mouse_type;
reg  [7:0]   drv_kbd_mouse_data;
reg  [64:0]  drv_rtc;
reg          drv_IO_UIO;
reg          drv_IO_FPGA;
reg          drv_IO_STROBE;
reg  [15:0]  drv_IO_DIN;
reg          drv_toccata_ena;
reg  [7:0]   drv_toccata_base;
reg          drv_a2065_ena;
reg  [7:0]   drv_a2065_base;
reg  [7:0]   drv_cdtv_ac_rom_byte;
reg          drv_cdtv_cmd_in_pop;
reg          drv_cdtv_cmd_out_push;
reg  [7:0]   drv_cdtv_cmd_out_data;
reg          drv_cdtv_sec_byte_push;
reg  [7:0]   drv_cdtv_sec_byte_data;
reg          drv_cdtv_subq_push;
reg  [7:0]   drv_cdtv_subq_byte;
reg          drv_cdtv_stch_pulse;
reg          drv_cdtv_stch_ack_clr;
reg          drv_cdtv_sten_pulse;
reg          drv_cdtv_scor_pulse;
reg          drv_cdtv_sbcp_pulse;
reg          drv_cdtv_dma_ack;
reg  [13:0]  drv_cdtv_nvr_load_addr;
reg  [7:0]   drv_cdtv_nvr_load_din;
reg          drv_cdtv_nvr_load_we;
reg  [13:0]  drv_cdtv_nvr_save_addr;
reg          drv_cdtv_nvr_clear_dirty;
reg          drv_ide_ext_irq;
reg          drv_akiko_irq;
reg  [4:0]   drv_ide_address;
reg          drv_ide_write;
reg  [15:0]  drv_ide_writedata;
reg          drv_ide_read;
reg          drv_a2065_clk_ddr;
reg  [63:0]  drv_a2065_mem_readdata;
reg          drv_a2065_mem_readdatavalid;
reg          drv_a2065_mem_waitrequest;
reg  [6:0]   drv_USER_IN;
reg  [3:0]   drv_ss_map_in;
reg          drv_ss_map_we;
reg  [190:0] drv_ss_cia_a_in;
reg  [202:0] drv_ss_cia_b_in;
reg          drv_ss_cia_we;

assign cpu_address = drv_cpu_address;
assign cpudata_in = drv_cpudata_in;
assign _cpu_as = drv__cpu_as;
assign _cpu_uds = drv__cpu_uds;
assign _cpu_lds = drv__cpu_lds;
assign cpu_r_w = drv_cpu_r_w;
assign _cpu_reset_in = drv__cpu_reset_in;
assign nmi_addr = drv_nmi_addr;
assign ramdata_in = drv_ramdata_in;
assign chip48 = drv_chip48;
assign rst_ext = drv_rst_ext;
assign rxd = drv_rxd;
assign cts = drv_cts;
assign dsr = drv_dsr;
assign cd = drv_cd;
assign ri = drv_ri;
assign _joy1 = drv__joy1;
assign _joy2 = drv__joy2;
assign _joy3 = drv__joy3;
assign _joy4 = drv__joy4;
assign joya1 = drv_joya1;
assign joya2 = drv_joya2;
assign mouse_btn = drv_mouse_btn;
assign kms_level = drv_kms_level;
assign kbd_mouse_type = drv_kbd_mouse_type;
assign kbd_mouse_data = drv_kbd_mouse_data;
assign rtc = drv_rtc;
assign IO_UIO = drv_IO_UIO;
assign IO_FPGA = drv_IO_FPGA;
assign IO_STROBE = drv_IO_STROBE;
assign IO_DIN = drv_IO_DIN;
assign toccata_ena = drv_toccata_ena;
assign toccata_base = drv_toccata_base;
assign a2065_ena = drv_a2065_ena;
assign a2065_base = drv_a2065_base;
assign cdtv_ac_rom_byte = drv_cdtv_ac_rom_byte;
assign cdtv_cmd_in_pop = drv_cdtv_cmd_in_pop;
assign cdtv_cmd_out_push = drv_cdtv_cmd_out_push;
assign cdtv_cmd_out_data = drv_cdtv_cmd_out_data;
assign cdtv_sec_byte_push = drv_cdtv_sec_byte_push;
assign cdtv_sec_byte_data = drv_cdtv_sec_byte_data;
assign cdtv_subq_push = drv_cdtv_subq_push;
assign cdtv_subq_byte = drv_cdtv_subq_byte;
assign cdtv_stch_pulse = drv_cdtv_stch_pulse;
assign cdtv_stch_ack_clr = drv_cdtv_stch_ack_clr;
assign cdtv_sten_pulse = drv_cdtv_sten_pulse;
assign cdtv_scor_pulse = drv_cdtv_scor_pulse;
assign cdtv_sbcp_pulse = drv_cdtv_sbcp_pulse;
assign cdtv_dma_ack = drv_cdtv_dma_ack;
assign cdtv_nvr_load_addr = drv_cdtv_nvr_load_addr;
assign cdtv_nvr_load_din = drv_cdtv_nvr_load_din;
assign cdtv_nvr_load_we = drv_cdtv_nvr_load_we;
assign cdtv_nvr_save_addr = drv_cdtv_nvr_save_addr;
assign cdtv_nvr_clear_dirty = drv_cdtv_nvr_clear_dirty;
assign ide_ext_irq = drv_ide_ext_irq;
assign akiko_irq = drv_akiko_irq;
assign ide_address = drv_ide_address;
assign ide_write = drv_ide_write;
assign ide_writedata = drv_ide_writedata;
assign ide_read = drv_ide_read;
assign a2065_clk_ddr = drv_a2065_clk_ddr;
assign a2065_mem_readdata = drv_a2065_mem_readdata;
assign a2065_mem_readdatavalid = drv_a2065_mem_readdatavalid;
assign a2065_mem_waitrequest = drv_a2065_mem_waitrequest;
assign USER_IN = drv_USER_IN;
assign ss_map_in = drv_ss_map_in;
assign ss_map_we = drv_ss_map_we;
assign ss_cia_a_in = drv_ss_cia_a_in;
assign ss_cia_b_in = drv_ss_cia_b_in;
assign ss_cia_we = drv_ss_cia_we;

// -------------------------------------------------------- all inputs low
task pins_reset_inputs;
begin
	drv_cpu_address = 0;
	drv_cpudata_in = 0;
	drv__cpu_as = 0;
	drv__cpu_uds = 0;
	drv__cpu_lds = 0;
	drv_cpu_r_w = 0;
	drv__cpu_reset_in = 0;
	drv_nmi_addr = 0;
	drv_ramdata_in = 0;
	drv_chip48 = 0;
	drv_rst_ext = 0;
	drv_rxd = 0;
	drv_cts = 0;
	drv_dsr = 0;
	drv_cd = 0;
	drv_ri = 0;
	drv__joy1 = 0;
	drv__joy2 = 0;
	drv__joy3 = 0;
	drv__joy4 = 0;
	drv_joya1 = 0;
	drv_joya2 = 0;
	drv_mouse_btn = 0;
	drv_kms_level = 0;
	drv_kbd_mouse_type = 0;
	drv_kbd_mouse_data = 0;
	drv_rtc = 0;
	drv_IO_UIO = 0;
	drv_IO_FPGA = 0;
	drv_IO_STROBE = 0;
	drv_IO_DIN = 0;
	drv_toccata_ena = 0;
	drv_toccata_base = 0;
	drv_a2065_ena = 0;
	drv_a2065_base = 0;
	drv_cdtv_ac_rom_byte = 0;
	drv_cdtv_cmd_in_pop = 0;
	drv_cdtv_cmd_out_push = 0;
	drv_cdtv_cmd_out_data = 0;
	drv_cdtv_sec_byte_push = 0;
	drv_cdtv_sec_byte_data = 0;
	drv_cdtv_subq_push = 0;
	drv_cdtv_subq_byte = 0;
	drv_cdtv_stch_pulse = 0;
	drv_cdtv_stch_ack_clr = 0;
	drv_cdtv_sten_pulse = 0;
	drv_cdtv_scor_pulse = 0;
	drv_cdtv_sbcp_pulse = 0;
	drv_cdtv_dma_ack = 0;
	drv_cdtv_nvr_load_addr = 0;
	drv_cdtv_nvr_load_din = 0;
	drv_cdtv_nvr_load_we = 0;
	drv_cdtv_nvr_save_addr = 0;
	drv_cdtv_nvr_clear_dirty = 0;
	drv_ide_ext_irq = 0;
	drv_akiko_irq = 0;
	drv_ide_address = 0;
	drv_ide_write = 0;
	drv_ide_writedata = 0;
	drv_ide_read = 0;
	drv_a2065_clk_ddr = 0;
	drv_a2065_mem_readdata = 0;
	drv_a2065_mem_readdatavalid = 0;
	drv_a2065_mem_waitrequest = 0;
	drv_USER_IN = 0;
	drv_ss_map_in = 0;
	drv_ss_map_we = 0;
	drv_ss_cia_a_in = 0;
	drv_ss_cia_b_in = 0;
	drv_ss_cia_we = 0;
end
endtask

// ------------------------------------------------------------------ DUT
minimig dut (
	.cpu_address(cpu_address),
	.cpu_data(cpu_data),
	.cpudata_in(cpudata_in),
	._cpu_ipl(_cpu_ipl),
	._cpu_as(_cpu_as),
	._cpu_uds(_cpu_uds),
	._cpu_lds(_cpu_lds),
	.cpu_r_w(cpu_r_w),
	._cpu_dtack(_cpu_dtack),
	._cpu_reset(_cpu_reset),
	._cpu_reset_in(_cpu_reset_in),
	.nmi_addr(nmi_addr),
	.ovr(ovr),
	.ram_data(ram_data),
	.ramdata_in(ramdata_in),
	.ram_address(ram_address),
	._ram_bhe(_ram_bhe),
	._ram_ble(_ram_ble),
	._ram_we(_ram_we),
	._ram_oe(_ram_oe),
	.chip48(chip48),
	.rst_ext(rst_ext),
	.rst_out(rst_out),
	.clk(clk),
	.clk7_en(clk7_en),
	.clk7n_en(clk7n_en),
	.c1(c1),
	.c3(c3),
	.cck(cck),
	.eclk(eclk),
	.rxd(rxd),
	.txd(txd),
	.cts(cts),
	.rts(rts),
	.dtr(dtr),
	.dsr(dsr),
	.cd(cd),
	.ri(ri),
	._joy1(_joy1),
	._joy2(_joy2),
	._joy3(_joy3),
	._joy4(_joy4),
	.joya1(joya1),
	.joya2(joya2),
	.mouse_btn(mouse_btn),
	.kms_level(kms_level),
	.kbd_mouse_type(kbd_mouse_type),
	.kbd_mouse_data(kbd_mouse_data),
	.pwr_led(pwr_led),
	.fdd_led(fdd_led),
	.hdd_led(hdd_led),
	.rtc(rtc),
	.IO_UIO(IO_UIO),
	.IO_FPGA(IO_FPGA),
	.IO_STROBE(IO_STROBE),
	.IO_WAIT(IO_WAIT),
	.IO_DIN(IO_DIN),
	.IO_DOUT(IO_DOUT),
	._hsync(_hsync),
	._vsync(_vsync),
	._csync(_csync),
	.field1(field1),
	.lace(lace),
	.hblank(hblank),
	.vblank(vblank),
	.red(red),
	.green(green),
	.blue(blue),
	.ar(ar),
	.scanline(scanline),
	.ce_pix(ce_pix),
	.res(res),
	.ntsc(ntsc),
	.ldata(ldata),
	.rdata(rdata),
	.ldata_okk(ldata_okk),
	.rdata_okk(rdata_okk),
	.aud_mix(aud_mix),
	.toccata_ena(toccata_ena),
	.toccata_base(toccata_base),
	.toccata_aud_left(toccata_aud_left),
	.toccata_aud_right(toccata_aud_right),
	.a2065_ena(a2065_ena),
	.a2065_base(a2065_base),
	.cdtv_mode(cdtv_mode),
	.cdtv_din(cdtv_din),
	.cdtv_selack(cdtv_selack),
	.cdtv_ac_rom_addr(cdtv_ac_rom_addr),
	.cdtv_ac_rom_byte(cdtv_ac_rom_byte),
	.cdtv_cmd_in_pop(cdtv_cmd_in_pop),
	.cdtv_cmd_in_pending(cdtv_cmd_in_pending),
	.cdtv_cmd_in_byte(cdtv_cmd_in_byte),
	.cdtv_cmd_out_push(cdtv_cmd_out_push),
	.cdtv_cmd_out_data(cdtv_cmd_out_data),
	.cdtv_sec_byte_push(cdtv_sec_byte_push),
	.cdtv_sec_byte_data(cdtv_sec_byte_data),
	.cdtv_sec_space(cdtv_sec_space),
	.cdtv_sec_fifo_empty(cdtv_sec_fifo_empty),
	.cdtv_subq_push(cdtv_subq_push),
	.cdtv_subq_byte(cdtv_subq_byte),
	.cdtv_stch_pulse(cdtv_stch_pulse),
	.cdtv_stch_ack(cdtv_stch_ack),
	.cdtv_stch_ack_clr(cdtv_stch_ack_clr),
	.cdtv_sten_pulse(cdtv_sten_pulse),
	.cdtv_scor_pulse(cdtv_scor_pulse),
	.cdtv_sbcp_pulse(cdtv_sbcp_pulse),
	.cdtv_dma_req(cdtv_dma_req),
	.cdtv_dma_we(cdtv_dma_we),
	.cdtv_dma_baddr(cdtv_dma_baddr),
	.cdtv_dma_wbyte(cdtv_dma_wbyte),
	.cdtv_dma_ack(cdtv_dma_ack),
	.cdtv_nvr_load_addr(cdtv_nvr_load_addr),
	.cdtv_nvr_load_din(cdtv_nvr_load_din),
	.cdtv_nvr_load_we(cdtv_nvr_load_we),
	.cdtv_nvr_save_addr(cdtv_nvr_save_addr),
	.cdtv_nvr_save_dout(cdtv_nvr_save_dout),
	.cdtv_nvr_dirty(cdtv_nvr_dirty),
	.cdtv_nvr_clear_dirty(cdtv_nvr_clear_dirty),
	.cdtv_cdda_volume(cdtv_cdda_volume),
	.cpucfg(cpucfg),
	.cachecfg(cachecfg),
	.memcfg(memcfg),
	.bootrom(bootrom),
	.ide_ena(ide_ena),
	.ide_fast(ide_fast),
	.ide_ext_irq(ide_ext_irq),
	.akiko_irq(akiko_irq),
	.ide_req(ide_req),
	.ide_address(ide_address),
	.ide_write(ide_write),
	.ide_writedata(ide_writedata),
	.ide_read(ide_read),
	.ide_readdata(ide_readdata),
	.a2065_clk_ddr(a2065_clk_ddr),
	.a2065_mem_address(a2065_mem_address),
	.a2065_mem_burstcount(a2065_mem_burstcount),
	.a2065_mem_read(a2065_mem_read),
	.a2065_mem_readdata(a2065_mem_readdata),
	.a2065_mem_readdatavalid(a2065_mem_readdatavalid),
	.a2065_mem_writedata(a2065_mem_writedata),
	.a2065_mem_byteenable(a2065_mem_byteenable),
	.a2065_mem_write(a2065_mem_write),
	.a2065_mem_waitrequest(a2065_mem_waitrequest),
	.USER_IN(USER_IN),
	.USER_OUT(USER_OUT),
	.user_port_mode(user_port_mode),
	.snac_mode(snac_mode),
	.mister_floppy_status(mister_floppy_status),
	.ss_blit_busy(ss_blit_busy),
	.ss_disk_busy(ss_disk_busy),
	.ss_audio_busy(ss_audio_busy),
	.ss_intreq(ss_intreq),
	.ss_intena(ss_intena),
	.ss_rga_addr(ss_rga_addr),
	.ss_rga_data(ss_rga_data),
	.ss_replay_we(ss_replay_we),
	.ss_replay_addr(ss_replay_addr),
	.ss_replay_data(ss_replay_data),
	.ss_replay_tick(ss_replay_tick),
	.ss_map(ss_map),
	.ss_map_in(ss_map_in),
	.ss_map_we(ss_map_we),
	.ss_cia_a(ss_cia_a),
	.ss_cia_b(ss_cia_b),
	.ss_cia_a_in(ss_cia_a_in),
	.ss_cia_b_in(ss_cia_b_in),
	.ss_cia_we(ss_cia_we)
);
